### PR TITLE
MemoryStorage + DemoStorage. Fixes #23

### LINKED ISSUE #23: Support for DemoStorage + MappingStorage
It is very useful to use a `DemoStorage` on top of a `MappingStorage`, for instance in unit testing with support for conflicts resolution (`MappingStorage` cannot solve conflicts, but `DemoStorage+MappingStorage` can).
Thus, I would love zodburi to handle this.
```python
import zodburi
factory, args = zodburi.resolve_uri("memory://storagename?demostorage=true")
# KeyError: 'Unrecognized database keyword(s): demostorage'
```

What do you think?

### PR DESCRIPTION
**Pull request by azmeuk**
Fixes #23

### CODE REVIEW

**Comment by azmeuk** [comment]
@tseaver What do you think about this PR?

**Comment by stevepiercy** [comment]
@jimfulton is another maintainer who can review and comment.

**Comment by tseaver** [comment]
I actually can't see much win for this feature in practice:  creating a `DemoStorage` + `FileStorage` against a tempfile gives the same effect (no existing records).  With a `MappingStorage`, what is the advantage of wrapping a `DemoStorage` around it?  There is no "precious" backing store to protect:  just create another `MappingStorage` if needed.

**Comment by azmeuk** [comment]
> With a MappingStorage, what is the advantage of wrapping a DemoStorage around it?
The advantage is conflict resolution.

As I explained in #23, I have a lot of unit test, and thus I would like to have a storage in the RAM. Some of my unit tests are testing some custom conflict resolution methods. As MappingStorage do not solve conflicts, I need to put a DemoStorage around to make all of this work.

**Comment by jimfulton** [comment]
I agree that it should be possible to use mapping-storage-backed demo storage, because, as @azmeuk pointed out, MappingStorage doesn't provide a complete implementation of the storage APIs.

Sorry I haven't had time to review this.

**Comment by azmeuk** [comment]
Hello. Any news about this PR?

**Comment by azmeuk** [comment]
Im a sorry to insist.
Can this PR be merged now? @stevepiercy?

**Comment by stevepiercy** [comment]
@azmeuk I am not a maintainer of this project. @jimfulton or @tseaver are [maintainers](https://pypi.org/project/zodburi/).

**Comment by tseaver** [comment]
@jimfulton I've just checked, and the [`DemoStorage` constructor](https://github.com/zopefoundation/ZODB/blob/79fe4737e3df5916bd4ce48d49b65caf26000cd4/src/ZODB/DemoStorage.py#L60-L97) already uses `MemoryStorage` as a base if no base is provided.

ISTM that a rather than hacking the `MappingStorageURIResolver` as this PR does, a better implmentation would be to add a new `DemoStorageURIResolver`.

**Comment by azmeuk** [comment]
@tseaver 
[FileStorageURIResolver](https://github.com/Pylons/zodburi/blob/master/zodburi/resolvers.py#L71) and [ClientStorageURIResolver](https://github.com/Pylons/zodburi/blob/master/zodburi/resolvers.py#L127) already have a `demostorage` URI argument. This is why I thought that also should `MemoryStorageURIResolver`.

I can do a new pull request with a DemostorageURIResolver though.

What do you think?

**Comment by azmeuk** [comment]
I would really like to go on with this pull requests.
@tseaver what do you think of my previous answer?

**Comment by azmeuk** [comment]
I apologize for insisting, but I would really love to find a solution.
@jimfulton @tseaver Do you have any new thought about this?

**Comment by azmeuk** [comment]
Months later I still apologize for insisting. I think this question could be quickly settled. @tseaver what do you think of my [august 25](https://github.com/Pylons/zodburi/pull/25#issuecomment-524627815) comment?

**Comment by tseaver** [comment]
@azmeuk Given that a `DemoStorage` already uses `MemoryStorage` as its default backend, I would still prefer to merge a PR which added a `DemoStorageURIResolver`.

**Comment by azmeuk** [comment]
Ok. I will try to submit another PR today.

**Comment by tseaver** [comment]
@azmeuk I think the URL format would look something like:  `demo://memory?<memory QS parms>`. with the `memory` part as optional.  We could then deprecate the `memory://` scheme altogether.

Perhaps we could also support `demo://file/<path-to_fs>?<file QS parms>` and likewise for `demo://zeo/<host>/port?<zeo QS parms>` / `demo://zeo/path/to/socket.zeo?<zeo QS params>`? We could then deprecate the `demostorage` QS params for those schemes.

**Comment by azmeuk** [comment]
I have been thinking a bit about this:

With the URL format you propose, how to distinguish `DemoStorage` querystring from the substorage querystring? (say `MemoryStorage` or `ClientStorage`) Should we mix all the querystring together, and let the factory choosing which argument is for `DemoStorage` and which one is for the substorage? So that would give `demo://memory?<memory QS params>&<demostorage QS params>`

There may be difficulties with the `name` argument that is common to several storages (for instance DemoStorage and MappingStorage).

**Comment by navytux** [comment]
For the reference: https://github.com/Pylons/zodburi/pull/29 adds support for `demo:` URI resolver.

**Comment by bertjwregeer** [comment]
After a long discussion and maintainer timeout, I have merged #29, I hope this solves the problem for you as well @azmeuk!

**Pull request closed without merging**
