### PR TITLE
Add missing ClientStorage constructor kw args to resolver.

### PR DESCRIPTION
**Pull request by tkoym**
I needed to be able to pass a blob_cache_size argument in the URI, but the resolver was tossing it out. I added it and other ClientStorage constructor keyword arguments that weren't being recognized by the resolver.

By the way, this is my first pull request. If I should have done something different, let me know.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@tkoym especially when adding a feature, PRs must include tests and docs. Also if you have not done so already, you must sign [CONTRIBUTORS.txt](https://github.com/Pylons/zodburi/blob/master/CONTRIBUTORS.txt).

Technical review would come from one of the maintainers, either @chrisrossi or @tseaver

**Comment by tseaver** [comment]
@stevepiercy [test coverage](https://github.com/Pylons/zodburi/pull/8/files#diff-f4770f9aa99cff076b37778d36ea7ce1R271) looks fine for this PR.

@tkoym The docs change needed is to the "`zeo://` URI scheme" section of https://github.com/Pylons/zodburi/blob/master/docs/index.rst

And to please add your name and the date to `CONTRIBUTORS.txt.

**Comment by tkoym** [comment]
I changed the docs and added my name to the list of contributors.

**Comment by stevepiercy** [comment]
@tkoym please pull in CONTRIBUTORS.txt from Pylons/zodburi master branch, merge, then push the merge commit to this branch again. I recently signed it, and that's why we have a conflict and cannot merge here. Sorry for the inconvenience.

**Comment by tkoym** [comment]
Being my first pull request, it took me a while to figure out how to merge the changes from the Plylons/zodburi master branch. Let me know if I didn't do it quite right.

**Comment by tseaver** [comment]
Thanks, @tkoym for your contribution!

**Pull request merged**
